service: kai-voice-token-server

provider:
  name: aws
  runtime: python3.9
  region: ${env:AWS_REGION, 'ap-southeast-1'}
  memorySize: 256
  timeout: 30
  environment:
    CUSTOM_AWS_REGION: ${env:AWS_REGION}
    AWS_SECRET_NAME: ${env:AWS_SECRET_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
        - secretsmanager:DescribeSecret
      Resource: 
        - arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:${env:AWS_SECRET_NAME}*
functions:
  api:
    handler: lambda_handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

package:
  patterns:
    - '!venv/**'
    - '!.env'
    - '!.env.example'
    - '!.git/**'
    - '!.gitignore'
    - '!.pytest_cache/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!tests/**'
    - '!serverless.yml'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: true
